
type AUDIO_PAYLOAD = 'audio_payload'
type TEXT_PAYLOAD = 'text_payload'
type CALLBACK_QUERY_PAYLOAD = 'callback_query_payload'

type MESSAGE_PAYLOAD_TYPE = AUDIO_PAYLOAD | TEXT_PAYLOAD | CALLBACK_QUERY_PAYLOAD

export {MESSAGE_PAYLOAD_TYPE}