
type PRIVATE_UPDATE_TYPE =  'text' | 'callback_query'

type CHANNEL_UPDATE_TYPE = 'channel_post'

type CHAT_UPDATE_TYPE = 'new_chat_photo'

type SCOPE_UPDATE_TYPE = PRIVATE_UPDATE_TYPE | CHANNEL_UPDATE_TYPE | CHAT_UPDATE_TYPE


export {PRIVATE_UPDATE_TYPE, CHANNEL_UPDATE_TYPE, CHAT_UPDATE_TYPE, SCOPE_UPDATE_TYPE}