
type CHANNEL_UPDATE_SCOPE = 'channel_scope'
type CHAT_UPDATE_SCOPE = 'chat_scope'
type PRIVATE_UPDATE_SCOPE = 'private_scope'

type BOT_UPDATE_SCOPE = CHANNEL_UPDATE_SCOPE | CHAT_UPDATE_SCOPE | PRIVATE_UPDATE_SCOPE

export {BOT_UPDATE_SCOPE, CHANNEL_UPDATE_SCOPE, CHAT_UPDATE_SCOPE, PRIVATE_UPDATE_SCOPE}